//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario1._2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ROL
    {
        public ROL()
        {
            this.PERMISOS = new HashSet<PERMISOS>();
            this.USUARIO = new HashSet<USUARIO>();
        }

        [Display(Name = "#")]
        public int IdRol { get; set; }

        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }

        [Display(Name = "Activo")]
        public Nullable<bool> Activo { get; set; }
        [Display(Name = "Fecha de Registro")]
        [DisplayFormat(ApplyFormatInEditMode = true,DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual ICollection<PERMISOS> PERMISOS { get; set; }
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
