//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario1._2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TIENDA
    {
        public TIENDA()
        {
            this.COMPRA = new HashSet<COMPRA>();
            this.PRODUCTO_TIENDA = new HashSet<PRODUCTO_TIENDA>();
            this.USUARIO = new HashSet<USUARIO>();
            this.VENTA = new HashSet<VENTA>();
        }

        [Display(Name = "ID")]
        public int IdTienda { get; set; }
        [Display(Name = "NOMBRE")]
        public string Nombre { get; set; }
        [Display(Name = "RUC")]
        public string RUC { get; set; }
        [Display(Name = "DIRECCION")]
        public string Direccion { get; set; }
        [Display(Name = "TELEFONO")]
        public string Telefono { get; set; }
        [Display(Name = "ACTIVO")]
        public Nullable<bool> Activo { get; set; }
        [Display(Name = "Fecha de Registro")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual ICollection<COMPRA> COMPRA { get; set; }
        public virtual ICollection<PRODUCTO_TIENDA> PRODUCTO_TIENDA { get; set; }
        public virtual ICollection<USUARIO> USUARIO { get; set; }
        public virtual ICollection<VENTA> VENTA { get; set; }
    }
}
