//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario1._2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIENDA
    {
        public TIENDA()
        {
            this.COMPRA = new HashSet<COMPRA>();
            this.PRODUCTO_TIENDA = new HashSet<PRODUCTO_TIENDA>();
            this.USUARIO = new HashSet<USUARIO>();
            this.VENTA = new HashSet<VENTA>();
        }
    
        public int IdTienda { get; set; }
        public string Nombre { get; set; }
        public string RUC { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual ICollection<COMPRA> COMPRA { get; set; }
        public virtual ICollection<PRODUCTO_TIENDA> PRODUCTO_TIENDA { get; set; }
        public virtual ICollection<USUARIO> USUARIO { get; set; }
        public virtual ICollection<VENTA> VENTA { get; set; }
    }
}
